      PROGRAM GRAPHIC
      
      INTEGER NRROWS, NRCOLS
      PARAMETER (NRROWS = 17, NRCOLS = 48)
      CHARACTER STAR *1, BLANK *1
      PARAMETER (STAR = '*', BLANK = ' ')
      INTEGER ROW, COL, STRTCL, STOPCL
      CHARACTER GRAPH (1:NRROWS, 1:NRCOLS) *1

C     START WITH A BLOCK OF STARS
      DO 28 ROW = 1, NRROWS
         DO 18 COL = 1, NRCOLS
            GRAPH (ROW, COL) = STAR
   18    CONTINUE
   28 CONTINUE

C     SUPERIMPOSE A BLOCK OF BLANKS IN THE MIDDLE
C     LEAVING A BORDER OF STARS
      DO 48 ROW = 3, NRROWS - 2
         DO 38 COL = 4, NRCOLS - 3
            GRAPH (ROW, COL) = BLANK
   38    CONTINUE
   48 CONTINUE

C     DIAGONAL BAR FROM UPPER LEFT TO LOWER RIGHT
      STRTCL = 4
      DO 68 ROW = 3, NRROWS - 2
         DO 58 COL = STRTCL, STRTCL + 5
            GRAPH (ROW, COL) = STAR
   58    CONTINUE
         STRTCL = STRTCL + 3
   68 CONTINUE

C     DIAGONAL BAR FROM UPPER RIGHT TO LOWER LEFT
      STOPCL = NRCOLS - 3
      DO 88 ROW = 3, NRROWS - 2
         DO 78 COL = STOPCL - 5, STOPCL
            GRAPH (ROW, COL) = STAR
   78    CONTINUE
         STOPCL = STOPCL - 3
   88 CONTINUE

C     PRINT THE GRAPHIC
      DO 98 ROW = 1, NRROWS
         PRINT '(T3, 99A)',
     +          (GRAPH (ROW, COL), COL = 1, NRCOLS)
   98 CONTINUE
      END
      